### ISSUE TITLE
Coord Leakage

### ISSUE THREAD

**Issue by vophamthanhan** [SeraphJACK/SimpleLogin#1]
Could the authentication process happen before allowing the player to spawn into the world? If so, the server would stop giving out coordinates of a player's last location (for example their top secret base).

**Comment by SeraphJACK** [comment]
It's hard to put the authentication process happen before the player spawning, but how about just teleport the player to a place and teleport back after logging in?

**Comment by vophamthanhan** [comment]
I _could_ do that, but then it gets unnecessarily complicated, while the coords are still technically sent to the player on log in. A teleportation bodge would have to be either they are teleported on logout, or somehow change the player spawn location on log in. 

If possible, can the player login location be modified to send them to (0,0), then teleport them after authentication? (without leaking coords?)

**Comment by SeraphJACK** [comment]
Seems that feature needs using coremod, for we have to complete the authentication before player instance `readFromNBT`, and there's no event to deal with that.

**Comment by vophamthanhan** [comment]
Darn, is there a way to "override" a player's save location when they log out? that way they "log back in" at (0,0) for example? Is there a way to teleport _during_ a logout?

**Comment by vophamthanhan** [comment]
it's not mission critical, somewhat nitpicky

**Comment by SeraphJACK** [comment]
However, I find that it's possible to fix this, just check #5
