### ISSUE TITLE
为什么现在 simplelogin reset <name> 这条命令不存在了？

### ISSUE THREAD

**Issue by Dounx** [SeraphJACK/SimpleLogin#14]
如果不能通过这个指令重置玩家密码，那么还有什么方法吗？

**Comment by SeraphJACK** [comment]
为什么不能用指令？你希望用什么样的方法重置玩家的密码？目前来说只有用指令或者编辑密码文件/nbt(取决于你的储存方式)
-- 
SeraphJACK

**Comment by SeraphJACK** [comment]
> 为什么现在 simplelogin reset <name> 这条命令不存在了？

现在是 `/simplelogin unregister <name>`
