### ISSUE TITLE
Bug on name

### ISSUE THREAD

**Issue by XionioXMaster** [SeraphJACK/SimpleLogin#21]
There was such a bug. I recently entered a nickname with a small one, I got a second account (despair). Just on the server, some person also entered the nickname despair and calmly entered, but at the same time I was kicked on the Despair account and wrote the wrong password. When I entered, it probably kicked, but my mod spectator turned on, before I rebooted to the server

**Comment by SeraphJACK** [comment]
I don't really understand what your English means. Are you pasting something machine-translated here? If so, please stop doing that.

**Comment by XionioXMaster** [comment]
The thing is, if a player logs into the server with a capital letter, for example: Abyss, when I log in with the nickname abyss, I'll kick him from the server and he won't be able to log in
