### ISSUE TITLE
Login = Died

### ISSUE THREAD

**Issue by XionioXMaster** [SeraphJACK/SimpleLogin#22]
If you leave the game while standing over the block under which there is a void, you will die as soon as you enter the server, a great bug to lose all things

**Comment by SeraphJACK** [comment]
Cannot reproduce

**Comment by XionioXMaster** [comment]
In the sense? Perhaps you are 1 on the server, but I have a large server and players, when connected, fall under the block or die if they stand on 1 block under which there is a void, change the spectator - survival switch, because of this they get stuck in blocks
