### ISSUE TITLE
Death of a player when entering the server due to mode switching

### ISSUE THREAD

**Issue by XionioXMaster** [SeraphJACK/SimpleLogin#23]
When a player exits the server and then enters back, he falls under 1 block, the solution to this problem is to remove the transition from Spectator mode to Survival, or at least replace Spectator with Adventure

Video: https://youtu.be/LUf_3Dvkg4U

I am using the Mohist core but this error was observed on me and on Forge, perhaps it is due to some other mod? But changing Spectator to Adventure solved that problem!

Look at my answer to another topic here: https://github.com/SeraphJACK/SimpleLogin/issues/21

**Comment by SeraphJACK** [comment]
This is not what SimpleLogin is doing. SimpleLogin will set your position back before switching your game mode. I CANNOT reproduce this issue in an environment where only SimpleLogin exists.
