### ISSUE TITLE
Broken singleplayer

### ISSUE THREAD

**Issue by masmc05** [SeraphJACK/SimpleLogin#25]
I wanted to test my own modpack and entered a creative singleplayer world, it was broken, i was in survival without permissions (even in a cheat world), after enabling cheats trough a open to lan, i was insta mining, changing gamemode didn't change anything, and changing password trough command was crashing the game
[crash-2021-10-31_19.55.30-client.txt](https://github.com/SeraphJACK/SimpleLogin/files/7449448/crash-2021-10-31_19.55.30-client.txt)

after that i read latest updates, went to the multiplayer menu, wrote a password, then opened the world again and all worked fine

**Comment by SeraphJACK** [comment]
Can you upload the log?

**Comment by masmc05** [comment]
[with crash](https://github.com/SeraphJACK/SimpleLogin/files/7452189/2021-10-31-6.log)
[first time, without crash](https://github.com/SeraphJACK/SimpleLogin/files/7452190/2021-10-31-3.log)

**Comment by SeraphJACK** [comment]
Can you try [this build](https://ci.seraphjack.top/job/SimpleLogin-MC1.16.4/12/)?

**Comment by SeraphJACK** [comment]
If you're still experiencing issues, feel free to reopen this.
