### ISSUE TITLE
Upgrade password storage

### ISSUE THREAD

**Issue by disconsented** [SeraphJACK/SimpleLogin#3]
SHA256 is pretty easy to brute force, GPU attacks are especially effective. I recommend moving passwords over to Bcrypt or Argon2

**Comment by SeraphJACK** [comment]
Are you a bitcoin miner or something?

**Comment by SeraphJACK** [comment]
> Alright that's a joke

I'm considering.

**Comment by SeraphJACK** [comment]
I know little about cryptography so maybe I'm wrong.

But since the encryption is open to public, the only way to be more secure is moving to some asymmetric encryption methods like RSA, instead of these symmetric ones.

**Comment by SeraphJACK** [comment]
And by default users are using random generated UUID as password, maybe the security is not that important.

Also, you can use your own method to encrypt it and copy it into configuration.

**Comment by disconsented** [comment]
Bcrypt/Argon2/SHA256 are examples of hashing not encryption, the point is that you can't reverse them.

**Comment by SeraphJACK** [comment]
We don't have salt in this case.

**Comment by disconsented** [comment]
Not a real issue with either, the salt is randomly generated per password and storage in the same r ecord

**Comment by SeraphJACK** [comment]
So you need to copy the file instead of remember the password.

Then why not just use generated one?

**Comment by disconsented** [comment]
Users just need to remember the password, any library worth its salt (ha) will have a comparison function to handle that for you.

**Comment by SeraphJACK** [comment]
@Yesterday17

**Comment by SeraphJACK** [comment]
Check #4

**Comment by SeraphJACK** [comment]
However, since the check must be done at the server-side, there's still a possibility that someone can get the SHA256sum.
