### ISSUE TITLE
Players get stuck on login 1.18.2

### ISSUE THREAD

**Issue by XionioXMaster** [SeraphJACK/SimpleLogin#30]
[Players get stuck on login](https://media.discordapp.net/attachments/897871478542975057/961362079191793734/unknown.png?width=1191&height=670)

[latest (7).log](https://github.com/SeraphJACK/SimpleLogin/files/8430424/latest.7.log)

Sometimes players fail to enter the server and the file with UUID is not generated

**Comment by SeraphJACK** [comment]
Closing as no further information is provided.
