### ISSUE TITLE
1.19?

### ISSUE THREAD

**Issue by FaceCutter** [SeraphJACK/SimpleLogin#33]
Hi! I would like to know, should we expect 1.19 update for Simple Login mod?

**Comment by kazu851** [comment]
it would be great. 1.19 =)

**Comment by SeraphJACK** [comment]
I have ported the mod to 1.19, but forge for 1.19 is quite unstable and contains bug which causes SimpleLogin unable to work.

MinecraftForge/MinecraftForge/issues/8833

**Comment by SeraphJACK** [comment]
The basic functions are already ported. However, I'm not releasing it since the command autocomplete is still broken.
