### ISSUE TITLE
Is it possible to use this with MySql?

### ISSUE THREAD

**Issue by TimLiz** [SeraphJACK/SimpleLogin#34]
Is it possible to use this with MySql?

**Comment by SeraphJACK** [comment]
You can use whatever you want and you just need to write a custom StorageProvider.

**Comment by TimLiz** [comment]
> You can use whatever you want and you just need to write a custom StorageProvider.

What does it mean to write? And how to do it?

**Comment by SeraphJACK** [comment]
README.md:

> Custom storage providers
> If you're familiar with Java and forge mods, it won't be very hard.
> 
> You need to implement the top.seraphjack.simplelogin.server.storage.StorageProvider interface, and register your own provider before the server starts by calling top.seraphjack.simplelogin.server.SLRegistries.STORAGE_PROVIDERS::register.
