### ISSUE TITLE
Error when entering the server for the first time

### ISSUE THREAD

**Issue by nullr00tbyte** [SeraphJACK/SimpleLogin#41]
![image](https://user-images.githubusercontent.com/54600529/196986417-ded74c7e-5689-424f-9c89-1784c160c8f9.png)

When I try to enter the server again the message no longer appears, it is only in the first entry

**Comment by SeraphJACK** [comment]
Can you send the full `debug.log`?

**Comment by nullr00tbyte** [comment]
[debug.log](https://github.com/SeraphJACK/SimpleLogin/files/9833320/debug.log)

**Comment by SeraphJACK** [comment]
Please send the client `debug.log`

**Comment by zzzaitegui** [comment]
I'm getting the same error when joining for the first time, some people get it a few times, and some can't join at all as they get the error every time. Screenshot and debug logs below.
![2022-10-29_16 07 58](https://user-images.githubusercontent.com/109433274/198838396-a38c55f7-948f-4739-bff8-60dc064ec9a4.png)
[debug.log](https://github.com/SeraphJACK/SimpleLogin/files/9893919/debug.log)
[debug-1.log](https://github.com/SeraphJACK/SimpleLogin/files/9893920/debug-1.log)

**Comment by chipijuega** [comment]
esta muy bueno el funcionamiento y la idea. tengo un server 1.19.2 Mohist y me arroja el mismo error que reportan anteriormente. Espero que puedan solucionarlo pronto. Saludos.
