### ISSUE TITLE
Incompatible with FancyMenu

### ISSUE THREAD

**Issue by SrRapero720** [SeraphJACK/SimpleLogin#43]
Menu elements cannot be edited

![2023-03-20_12h39_12](https://user-images.githubusercontent.com/29090346/226435539-c065e179-f4d4-4794-8b8b-5b60933f3162.png)
![2023-03-20_12h39_18](https://user-images.githubusercontent.com/29090346/226435543-9d413dca-bbaf-48b7-9b01-ccc3c1deb9e2.png)

**Comment by SeraphJACK** [comment]
I'm sorry, but currently no plan to support it.

I don't think it matters much since this page will only appear once.

Feel free to reopen the issue if you have any use cases where it really matters :)
