### ISSUE TITLE
I don't wanna be that guy, but there's no auth mods for forge yet so 1.20?

### ISSUE THREAD

**Issue by ghost** [SeraphJACK/SimpleLogin#49]

**Comment by FrancisRDC** [comment]
The 1.19.2 version works in the 1.20.1 servers, had no problems in my server.

**Comment by S0lux** [comment]
> The 1.19.2 version works in the 1.20.1 servers, had no problems in my server.

but it crashes on 1.20.1 clients though, and the mod requires both client and server to have the it installed

**Comment by FrancisRDC** [comment]
> > The 1.19.2 version works in the 1.20.1 servers, had no problems in my server.
> 
> but it crashes on 1.20.1 clients though, and the mod requires both client and server to have the it installed

Maybe dependes on the Forge Version, I'm using the 1.20.1 - 47.1.44 version with no problem in client side and working as expected.

**Comment by DarkNasuada** [comment]
Well it ain't working for me either and I am using the latest version of forge. 

Probably cause its used in older Minecraft version it works. If u move your password file out of your Minecraft directory and boot 1.20.1 it will probably crash as well.

**Comment by S0lux** [comment]
> > > The 1.19.2 version works in the 1.20.1 servers, had no problems in my server.
> > 
> > 
> > but it crashes on 1.20.1 clients though, and the mod requires both client and server to have the it installed
> 
> Maybe dependes on the Forge Version, I'm using the 1.20.1 - 47.1.44 version with no problem in client side and working as expected.

I believe it only crashes if you don't have a password set yet.

**Comment by SeraphJACK** [comment]
Already released on CurseForge: https://legacy.curseforge.com/minecraft/mc-mods/simple-login/files/4745380

**Comment by DarkNasuada** [comment]
Thank you for your work.
