### ISSUE TITLE
The command /simplelogin setDefaultGameType does not work

### ISSUE THREAD

**Issue by Carl12345678912** [SeraphJACK/SimpleLogin#54]

**Comment by Carl12345678912** [comment]
![obrázek_2024-01-24_163133115](https://github.com/SeraphJACK/SimpleLogin/assets/116182716/4d4be019-682f-4d6e-aefa-0b24db58bfb2)

**Comment by SeraphJACK** [comment]
Have you tried TAB auto-complete? You may need to spell player name in lower-case

**Comment by Carl12345678912** [comment]
Ok i will try

**Comment by Carl12345678912** [comment]
it  works thanks
