### ISSUE TITLE
Clicking on the "mods" button on the title screen crashes the game instantly. It works fine without SimpleLogin active.

### ISSUE THREAD

**Issue by UnsexSituation** [SeraphJACK/SimpleLogin#55]
https://mclo.gs/knVu6Av

Forge: 1.19.2 build 43.3.7
SimpleLogin: 1.0.1

**Comment by SeraphJACK** [comment]
It is not caused by SimpleLogin.

Fuzss/diagonalfences#14

**Comment by UnsexSituation** [comment]
Deleted diagonalfences. Still happens. Here's the log.
https://mclo.gs/cxiLDlg

**Comment by SeraphJACK** [comment]
Cannot reproduce with only SimpleLogin installed.

Can you try to find out which mod together with SimpleLogin will cause this problem?

**Comment by UnsexSituation** [comment]
Sure. Will attempt.

**Comment by UnsexSituation** [comment]
Very sorry for wasting your time. I did a bit more digging and it turns out my launcher mistakenly installed the 1.0.2 version instead? On the mods list it was showing me 1.0.1, same in the crash log. Downgrading fixed the crashing.
