### ISSUE TITLE
mohist-1.16.5服务端无法通过控制台指令进行密码重置

### ISSUE THREAD

**Issue by invHvni** [SeraphJACK/SimpleLogin#57]
simplelogin unregister命令在游戏内op指令可正常重置密码
控制台输入会成功显示 Registry for player {player} does not exist但是没有重置效果
![image](https://github.com/SeraphJACK/SimpleLogin/assets/157210742/93855b8e-be45-44ee-b6fe-bd7951c3e1db)
![image](https://github.com/SeraphJACK/SimpleLogin/assets/157210742/4d027dbb-2fc0-4e26-9ec0-c05ef24fb7d1)

**Comment by SeraphJACK** [comment]
这条错误是提示对应的玩家不存在。如果你在游戏中已经 `unregister` 了，那么对应的玩家条目就已经被删除了。

**Comment by SeraphJACK** [comment]
可以在控制台尝试用 tab 补全列出所有注册的玩家

**Comment by invHvni** [comment]
好的,已经解决,非常感谢

**Comment by invHvni** [comment]
摸明白问题了,重置ID只能小写,哪怕ID本身有大写的也要改成小写才可以,希望后续可以优化一下这个东西吧
