### ISSUE TITLE
1.20.1版本，客服端没有密码文件，无法登录服务器

### ISSUE THREAD

**Issue by Sawtooth-IT** [SeraphJACK/SimpleLogin#60]

**Comment by SeraphJACK** [comment]
请详细描述你的问题，期望的行为，复现方式。

**Comment by Sawtooth-IT** [comment]
服务端与客户端安装同一版本，客户端进入游戏时一直显示加入世界中，卸载该模组后正常进入世界
![Uploading wx_camera_1711257285270.jpg…]()

**Comment by Sawtooth-IT** [comment]
游戏文件夹中也没有生成.sl_password文件

**Comment by SeraphJACK** [comment]
发一下游戏版本和日志

**Comment by Sawtooth-IT** [comment]
客户端日志
[minecraft-exported-logs-2024-03-26T16-43-57.log](https://github.com/SeraphJACK/SimpleLogin/files/14755359/minecraft-exported-logs-2024-03-26T16-43-57.log)
服务端日志
[latest.log](https://github.com/SeraphJACK/SimpleLogin/files/14755367/latest.log)
游戏版本1.20.1

**Comment by SeraphJACK** [comment]
使用了类似自定义 GUI 的模组吗？

**Comment by SeraphJACK** [comment]
正常游戏启动后 SimpleLogin 会有一个 GUI 提示配置密码。日志看起来是用户跳过了这个过程直接连接服务器了。

**Comment by Sawtooth-IT** [comment]
Modern UI算吗，启动游戏后没有要配置密码的gui

**Comment by SeraphJACK** [comment]
尝试卸载 ModernUI 试试，正常游戏刚启动就会有 GUI 要求设置密码的。
