### ISSUE TITLE
Java process will stall when trying to stop it

### ISSUE THREAD

**Issue by Pendrag00n** [SeraphJACK/SimpleLogin#61]
This happens around 25% of the time. The process still consumes resources so I suppose it's "doing something"
![image](https://github.com/SeraphJACK/SimpleLogin/assets/88731722/7609207b-8fcb-4353-b30f-663e567dbaf3)

**Comment by SeraphJACK** [comment]
See #39

**Comment by Pendrag00n** [comment]
This still happens. Forcefully killing the process doesn't seem to bring up any issues though

**Comment by SeraphJACK** [comment]
Do you read #39 ?

**Comment by Pendrag00n** [comment]
Yes, but it doesn't seem to help at all. Also, using `jps` to find out the PID of the instance will always render a different PID (I don't really know why) so I used `pgrep java`
I also couldn't find  anything using `jstack`. Maybe I missed it?
![jarvis](https://github.com/SeraphJACK/SimpleLogin/assets/88731722/3130bedb-adaf-4a98-bbed-de9ba6f77c03)

**Comment by SeraphJACK** [comment]
No you found it, it's just on your screenshot: pool-3-thread-1 is not a daemon so whoever spawned it is responsible for the process not exiting. SimpleLogin won't spawn such a process, so you need to find out which mod it is.

于 2024年6月25日 GMT+08:00 19:07:09，Pendrag00n ***@***.***> 写道：
>Yes, but it doesn't seem to help at all. Also, using `jps` to find out the PID of the instance will always render a different PID (I don't really know why) so I used `pgrep java`
>I also couldn't find  anything using `jstack`. Maybe I missed it?
>![jarvis](https://github.com/SeraphJACK/SimpleLogin/assets/88731722/3130bedb-adaf-4a98-bbed-de9ba6f77c03)
>
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/SeraphJACK/SimpleLogin/issues/61#issuecomment-2188643717
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>
SeraphJACK
