### ISSUE TITLE
Backport 1.7.10

### ISSUE THREAD

**Issue by TheVitya2127** [SeraphJACK/SimpleLogin#65]
will there be a backport mod for 1.7.10?

**Comment by SeraphJACK** [comment]
There's currently no plan for backport, sorry!

**Comment by TheVitya2127** [comment]
# It's a very pity

**Comment by Yesterday17** [comment]
Minecraft 1.7.10 just had its 10th birthday [yesterday](https://howoldisminecraft1710.today/).
<img width="1813" alt="image" src="https://github.com/SeraphJACK/SimpleLogin/assets/8667822/e5bdd8a7-ffa4-439c-836e-78f18df3653f">

**Comment by TheVitya2127** [comment]
![tenor](https://github.com/SeraphJACK/SimpleLogin/assets/119508042/2df4418c-7e46-4d70-98f3-b389e9cf4624)
