### ISSUE TITLE
Config file doesn't generate (1.20.1)

### ISSUE THREAD

**Issue by Theronguard** [SeraphJACK/SimpleLogin#66]
Hi. I'm using the SimpleLogin-1.20.1-1.0.2-all version and it seems the .cfg file doesn't generate for me (both on the server and the client). The mod is loaded though.

**Comment by SeraphJACK** [comment]
Sorry for the late reply.

The server configuration is probably generated under `world/serverconfig/`, and the client password is stored at `.minecraft/.sl_password`. Can you confirm?
