### ISSUE TITLE
how to remove password from server?

### ISSUE THREAD

**Issue by IshuCute** [SeraphJACK/SimpleLogin#70]
some "genius" people ignores password window even i marked this moment wit CAPS. but they anyway just generating random password and then come to me asking to reset their password, but i dont know how or posible is.

**Comment by fakeboboliu** [comment]
According to the code, you should: open "sl_entries.dat" in your world dir, it's a JSON file so you can simply delete any entry you want.

**Comment by IshuCute** [comment]
> According to the code, you should: open "sl_entries.dat" in your world dir, it's a JSON file so you can simply delete any entry you want.

i tried. old password just returns after restart

**Comment by fakeboboliu** [comment]
If you deleted in the right way, it should be your player's fault for registering old password again.
They should remove password in their cache to stop this before asking you to reset the password.

**Comment by SeraphJACK** [comment]
https://github.com/SeraphJACK/SimpleLogin?tab=readme-ov-file#commands

`/simplelogin unregister <PlayerName>`

Unregister the player.

Note that player names should be in lower case.
