### ISSUE TITLE
求个1.15.2版本

### ISSUE THREAD

**Issue by xxlio109** [SeraphJACK/SimpleLogin#8]
求个1.15.2版本，加油！

**Comment by SeraphJACK** [comment]
~~没有计划 back port ，而且 1.5.2 ...~~

**Comment by SeraphJACK** [comment]
~~不好意思1.15.2看成1.5.2了~~

近期正在把 mod 更新到 1.14.4，之后更新到 1.15.2 应该很容易。

**Comment by SeraphJACK** [comment]
[simplelogin-0.0.0-alpha.zip](https://github.com/SeraphJACK/SimpleLogin/files/4170266/simplelogin-0.0.0-alpha.zip) （自行把后缀名改成.jar，因为jar后缀不支持上传到 GitHub）

这是在 1.14.4 的环境下构建出的测试开发版，在 1.15.2 上应该也可以加载。如果方便的话能否帮忙测试一下还有哪些问题？

**Comment by SeraphJACK** [comment]
CurseForge 上也发布了[alpha版](https://www.curseforge.com/minecraft/mc-mods/simple-login/files/2877880)。
