### ISSUE TITLE
crash when  I press the respawn button

### ISSUE THREAD

**Issue by k4mix** [SeraphJACK/SimpleLogin#9]
When i press respawn button  server is crashing
[crash-2020-02-09_11.46.49-server.txt](https://github.com/SeraphJACK/SimpleLogin/files/4176879/crash-2020-02-09_11.46.49-server.txt)

when changing login timeout to 0 i can't join to the server

**Comment by k4mix** [comment]
version 1.15.2

**Comment by SeraphJACK** [comment]
If you change login timeout to 0, obviously you can't join. It defines the max milliseconds before a player login after joining the server.

The crash-report seems told that here's a thread issue, investigating.

**Comment by SeraphJACK** [comment]
Can you upload the log file to [Ubuntu paste](https://paste.ubuntu.com/)? Thanks!

**Comment by SeraphJACK** [comment]
I released a new version for Minecraft 1.15.2 on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/simple-login/files/2878700), maybe you should have a try.

**Comment by k4mix** [comment]
yea now it's working fine thx
